package info.statstrats.banindex;

import java.util.HashMap;
import java.util.Map;

public enum ChampionNameMap {

    INSTANCE;

    private Map<Integer, String> map = new HashMap<>(124);

    private ChampionNameMap() {
        map.put(1, "Annie");
        map.put(2, "Olaf");
        map.put(3, "Galio");
        map.put(4, "Twisted Fate");
        map.put(5, "Xin Zhao");
        map.put(6, "Urgot");
        map.put(7, "LeBlanc");
        map.put(8, "Vladimir");
        map.put(9, "Fiddlesticks");
        map.put(10, "Kayle");
        map.put(11, "Master Yi");
        map.put(12, "Alistar");
        map.put(13, "Ryze");
        map.put(14, "Sion");
        map.put(15, "Sivir");
        map.put(16, "Soraka");
        map.put(17, "Teemo");
        map.put(18, "Tristana");
        map.put(19, "Warwick");
        map.put(20, "Nunu");
        map.put(21, "Miss Fortune");
        map.put(22, "Ashe");
        map.put(23, "Tryndamere");
        map.put(24, "Jax");
        map.put(25, "Morgana");
        map.put(26, "Zilean");
        map.put(27, "Singed");
        map.put(28, "Evelynn");
        map.put(29, "Twitch");
        map.put(30, "Karthus");
        map.put(31, "Cho'Gath");
        map.put(32, "Amumu");
        map.put(33, "Rammus");
        map.put(34, "Anivia");
        map.put(35, "Shaco");
        map.put(36, "Dr. Mundo");
        map.put(37, "Sona");
        map.put(38, "Kassadin");
        map.put(39, "Irelia");
        map.put(40, "Janna");
        map.put(41, "Gangplank");
        map.put(42, "Corki");
        map.put(43, "Karma");
        map.put(44, "Taric");
        map.put(45, "Veigar");
        map.put(48, "Trundle");
        map.put(50, "Swain");
        map.put(51, "Caitlyn");
        map.put(53, "Blitzcrank");
        map.put(54, "Malphite");
        map.put(55, "Katarina");
        map.put(56, "Nocturne");
        map.put(57, "Maokai");
        map.put(58, "Renekton");
        map.put(59, "Jarvan IV");
        map.put(60, "Elise");
        map.put(61, "Orianna");
        map.put(62, "Wukong");
        map.put(63, "Brand");
        map.put(64, "Lee Sin");
        map.put(67, "Vayne");
        map.put(68, "Rumble");
        map.put(69, "Cassiopeia");
        map.put(72, "Skarner");
        map.put(74, "Heimerdinger");
        map.put(75, "Nasus");
        map.put(76, "Nidalee");
        map.put(77, "Udyr");
        map.put(78, "Poppy");
        map.put(79, "Gragas");
        map.put(80, "Pantheon");
        map.put(81, "Ezreal");
        map.put(82, "Mordekaiser");
        map.put(83, "Yorick");
        map.put(84, "Akali");
        map.put(85, "Kennen");
        map.put(86, "Garen");
        map.put(89, "Leona");
        map.put(90, "Malzahar");
        map.put(91, "Talon");
        map.put(92, "Riven");
        map.put(96, "Kog'Maw");
        map.put(98, "Shen");
        map.put(99, "Lux");
        map.put(101, "Xerath");
        map.put(102, "Shyvana");
        map.put(103, "Ahri");
        map.put(104, "Graves");
        map.put(105, "Fizz");
        map.put(106, "Volibear");
        map.put(107, "Rengar");
        map.put(110, "Varus");
        map.put(111, "Nautilus");
        map.put(112, "Viktor");
        map.put(113, "Sejuani");
        map.put(114, "Fiora");
        map.put(115, "Ziggs");
        map.put(117, "Lulu");
        map.put(119, "Draven");
        map.put(120, "Hecarim");
        map.put(121, "Kha'Zix");
        map.put(122, "Darius");
        map.put(126, "Jayce");
        map.put(127, "Lissandra");
        map.put(131, "Diana");
        map.put(133, "Quinn");
        map.put(134, "Syndra");
        map.put(143, "Zyra");
        map.put(150, "Gnar");
        map.put(154, "Zac");
        map.put(157, "Yasuo");
        map.put(161, "Vel'Koz");
        map.put(201, "Braum");
        map.put(222, "Jinx");
        map.put(236, "Lucian");
        map.put(238, "Zed");
        map.put(254, "Vi");
        map.put(266, "Aatrox");
        map.put(267, "Nami");
        map.put(268, "Azir");
        map.put(412, "Thresh");
        map.put(421, "Rek'Sai");
        map.put(429, "Kalista");
        map.put(432, "Bard");
    }

    public String getName(int id) {
        return map.get(id);
    }
}
